apiVersion: v1
kind: Service
metadata:
  name: chats-service
  labels:
    name: chats-service
    app: chatting-app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
     name: chats
     app: chatting-app