apiVersion: v1
kind: Pod
metadata:
  name: mongochat
  labels:
    name: mongochat
    app: chatting-app
spec:
  volumes:
  - name: db-chats-data
    persistentVolumeClaim:
      claimName: db-chats-data
  containers:
  - name: mongochat
    image: mongo:latest
    ports:
     - containerPort: 27017
    volumeMounts:
    - mountPath: /var/lib/mongo
      name: db-chats-data