apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongochat-service
    app: chatting-app
spec:
  ports:
  - port: 27017
    name: mongo-something
    targetPort: 27017
  selector:
     name: mongochat
     app: chatting-app