apiVersion: v1
kind: Service
metadata:
  name: db-userauth-service
  labels:
    name: db-userauth
    app: chatting-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
     name: db-userauth
     app: chatting-app